d := Constructor()
d.AddWord("day")
d.AddWord("bay")
d.AddWord("may")
d.AddWord("say")
Tests.BoolCheck("search day", d.Search("day") == true)
Tests.BoolCheck("search .ay", d.Search(".ay") == true)
Tests.BoolCheck("search b..", d.Search("b..") == true)
Tests.BoolCheck("search nope", d.Search("nope") == false)
