d = WordDictionary()
d.addWord("day")
d.addWord("bay")
d.addWord("may")
d.addWord("say")
Tests.bool_check("search day", d.search("day") == True)
Tests.bool_check("search .ay", d.search(".ay") == True)
Tests.bool_check("search b..", d.search("b..") == True)
Tests.bool_check("search nope", d.search("nope") == False)
